// Base de dados das Lojas (Store Locator Database)
const STORES_DATA = [
    {
        id: "loja-01",
        name: "TechWorld Megastore",
        category: "eletronicos",
        categoryName: "Eletrônicos & Tech",
        icon: "fa-laptop",
        rating: 4.8,
        reviewsCount: 342,
        image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=800&q=80",
        address: "Av. Paulista, 1230 - Bela Vista",
        city: "São Paulo",
        state: "SP",
        zipCode: "01310-100",
        lat: -23.561414,
        lng: -46.655881,
        phone: "(11) 3200-9000",
        whatsapp: "5511990008888",
        hours: {
            weekdays: "09:00 - 21:00",
            saturday: "10:00 - 20:00",
            sunday: "12:00 - 18:00",
            openHour: 9,
            closeHour: 21
        },
        facilities: ["wifi", "parking", "accessibility", "pickup"],
        description: "A maior loja de tecnologia e eletrônicos da região. Notebooks, smartphones, gadgets, consoles de videogame e assistência técnica especializada.",
        highlights: ["Desconto de 10% no Pix", "Assistência Técnica no Local", "Garantia Estendida"]
    },
    {
        id: "loja-02",
        name: "Boutique Bella Moda",
        category: "vestuario",
        categoryName: "Vestuário & Moda",
        icon: "fa-shirt",
        rating: 4.9,
        reviewsCount: 198,
        image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80",
        address: "Rua Oscar Freire, 840 - Jardins",
        city: "São Paulo",
        state: "SP",
        zipCode: "01426-000",
        lat: -23.563820,
        lng: -46.668500,
        phone: "(11) 3088-4455",
        whatsapp: "5511987654321",
        hours: {
            weekdays: "10:00 - 20:00",
            saturday: "10:00 - 20:00",
            sunday: "Fechado",
            openHour: 10,
            closeHour: 20
        },
        facilities: ["wifi", "parking", "pet"],
        description: "Roupas femininas e masculinas exclusivas, coleções de estilistas renomados, calçados e acessórios de alta qualidade.",
        highlights: ["Provador VIP", "Consultoria de Imagem", "Ajustes Grátis"]
    },
    {
        id: "loja-03",
        name: "Empório & Bistrô Gourmet",
        category: "gastronomia",
        categoryName: "Gastronomia & Alimentos",
        icon: "fa-utensils",
        rating: 4.7,
        reviewsCount: 512,
        image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80",
        address: "Rua Haddock Lobo, 1327 - Cerqueira César",
        city: "São Paulo",
        state: "SP",
        zipCode: "01414-003",
        lat: -23.560100,
        lng: -46.664200,
        phone: "(11) 3062-7700",
        whatsapp: "5511977771111",
        hours: {
            weekdays: "08:00 - 22:00",
            saturday: "08:00 - 23:00",
            sunday: "09:00 - 18:00",
            openHour: 8,
            closeHour: 22
        },
        facilities: ["wifi", "parking", "accessibility", "pet"],
        description: "Vinhos importados, queijos artesanais, frios nobres, cafés especiais e pratos deliciosos para consumo no local ou viagem.",
        highlights: ["Degustação de Vinhos", "Café da Manhã Colonial", "Produtos Orgânicos"]
    },
    {
        id: "loja-04",
        name: "Design & Conforto Casa",
        category: "casa",
        categoryName: "Casa & Decoração",
        icon: "fa-couch",
        rating: 4.6,
        reviewsCount: 145,
        image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
        address: "Av. das Nações Unidas, 12551 - SP Market",
        city: "São Paulo",
        state: "SP",
        zipCode: "04578-903",
        lat: -23.612500,
        lng: -46.699100,
        phone: "(11) 5181-2000",
        whatsapp: "5511966665555",
        hours: {
            weekdays: "10:00 - 22:00",
            saturday: "10:00 - 22:00",
            sunday: "14:00 - 20:00",
            openHour: 10,
            closeHour: 22
        },
        facilities: ["wifi", "parking", "accessibility", "pickup"],
        description: "Móveis planejados, iluminação decorativa, itens de organização e objetos de design para transformar qualquer ambiente.",
        highlights: ["Montagem Grátis", "Projeto 3D Gratuito", "Entrega Rápida"]
    },
    {
        id: "loja-05",
        name: "Glow & Care Cosméticos",
        category: "beleza",
        categoryName: "Beleza & Estética",
        icon: "fa-spa",
        rating: 4.9,
        reviewsCount: 276,
        image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
        address: "Rua Garcia d'Avila, 134 - Ipanema",
        city: "Rio de Janeiro",
        state: "RJ",
        zipCode: "22421-010",
        lat: -22.983900,
        lng: -43.207200,
        phone: "(21) 2523-9090",
        whatsapp: "5521988884444",
        hours: {
            weekdays: "09:00 - 20:00",
            saturday: "09:00 - 19:00",
            sunday: "Fechado",
            openHour: 9,
            closeHour: 20
        },
        facilities: ["wifi", "accessibility", "pickup"],
        description: "Skincare vegano, perfumes importados, maquiagens e tratamento capilar profissional. Atendimento personalizado por cosmetólogas.",
        highlights: ["Análise de Pele Grátis", "Brindes Exclusivos", "Marcas Cruelty-free"]
    },
    {
        id: "loja-06",
        name: "SportZone Performance",
        category: "vestuario",
        categoryName: "Vestuário & Esportes",
        icon: "fa-running",
        rating: 4.7,
        reviewsCount: 410,
        image: "https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=800&q=80",
        address: "Av. das Américas, 4666 - Barra da Tijuca",
        city: "Rio de Janeiro",
        state: "RJ",
        zipCode: "22640-102",
        lat: -23.000300,
        lng: -43.351200,
        phone: "(21) 3325-1100",
        whatsapp: "5521971112222",
        hours: {
            weekdays: "10:00 - 22:00",
            saturday: "10:00 - 22:00",
            sunday: "13:00 - 21:00",
            openHour: 10,
            closeHour: 22
        },
        facilities: ["wifi", "parking", "accessibility", "pickup"],
        description: "Equipamentos esportivos, tênis de corrida com teste de pisada, vestuário fitness e suplementação alimentar das melhores marcas.",
        highlights: ["Teste de Pisada 3D", "Oficina de Bicicletas", "Clube de Corrida"]
    },
    {
        id: "loja-07",
        name: "Livraria & Café Sabedoria",
        category: "conveniencia",
        categoryName: "Cultura & Conveniência",
        icon: "fa-book",
        rating: 4.9,
        reviewsCount: 630,
        image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=800&q=80",
        address: "Rua XV de Novembro, 450 - Centro",
        city: "Curitiba",
        state: "PR",
        zipCode: "80020-310",
        lat: -25.429700,
        lng: -49.271100,
        phone: "(41) 3224-8899",
        whatsapp: "5541999887766",
        hours: {
            weekdays: "08:30 - 20:00",
            saturday: "09:00 - 18:00",
            sunday: "10:00 - 16:00",
            openHour: 8.5,
            closeHour: 20
        },
        facilities: ["wifi", "pet", "accessibility"],
        description: "Amplo acervo de livros nacionais e importados, espaço para leitura acolhedor, cafeteria com grãos especiais e papelaria fofa.",
        highlights: ["Espaço Kids", "Clube do Livro Mensal", "WiFi Ultra Rápido"]
    },
    {
        id: "loja-08",
        name: "Mundo Pet & Vet 24h",
        category: "conveniencia",
        categoryName: "Pet & Conveniência",
        icon: "fa-paw",
        rating: 4.8,
        reviewsCount: 380,
        image: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=800&q=80",
        address: "Av. Afonso Pena, 2300 - Savassi",
        city: "Belo Horizonte",
        state: "MG",
        zipCode: "30130-007",
        lat: -19.928100,
        lng: -43.931200,
        phone: "(31) 3261-5050",
        whatsapp: "5531984443333",
        hours: {
            weekdays: "00:00 - 23:59",
            saturday: "00:00 - 23:59",
            sunday: "00:00 - 23:59",
            openHour: 0,
            closeHour: 24
        },
        facilities: ["wifi", "parking", "pet", "accessibility", "pickup"],
        description: "Rações super premium, brinquedos, farmácia veterinária, centro de estética pet (banho e tosa) e clínica veterinária 24 horas.",
        highlights: ["Atendimento Vet 24 Horas", "Taxi Pet", "Banho com Ozônio"]
    }
];
